version: "3.7"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Bangkok
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=fmc
      - N8N_BASIC_AUTH_PASSWORD=0947571333
      - N8N_HOST=n8n.example.com
      - WEBHOOK_URL=https://n8n.example.com/
      - N8N_PORT=5678
      - TZ=Asia/Bangkok
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
